version: "3.8"
services:
  backend:
    build: .
    container_name: backend-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=fintech
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    volumes:
      - fintech-data:/var/lib/postgresql/data

volumes:
  fintech-data:
