basePath: /
definitions:
  models.BalanceResult:
    properties:
      total_credits:
        type: number
      total_debits:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a simple API for handling financial transactions
  termsOfService: https://example.com/terms/
  title: FinTech Backend API
  version: "1.0"
paths:
  /migrate:
    post:
      consumes:
      - multipart/form-data
      description: Upload a CSV file with transaction data and migrate it to the database
      parameters:
      - description: CSV File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Migración completada con éxito
          schema:
            type: string
        "400":
          description: Error al recibir el archivo
          schema:
            type: string
        "500":
          description: Error al guardar la transacción
          schema:
            type: string
      summary: Upload transactions CSV and migrate to DB
  /users/{user_id}/balance:
    get:
      description: Get the balance of a user by user_id within a date range
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: From date
        example: '"2024-01-01T00:00:00Z"'
        in: query
        name: from
        type: string
      - description: To date
        example: '"2024-07-01T00:00:00Z"'
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BalanceResult'
        "400":
          description: Error al consultar el balance
          schema:
            type: string
        "404":
          description: Usuario no encontrado
          schema:
            type: string
      summary: Get the balance of a user within a date range
schemes:
- http
swagger: "2.0"
